models = [
    image: "process.png"
    data:
        [
                start: 
                    x:34
                    y:319
                end: 
                    x:47
                    y:333
            ,
                start:
                    x:114
                    y:315
                end:
                    x:130
                    y:335
            ,
                start:
                    x:195
                    y:151
                end:
                    x:284
                    y:221
            ,
                start:
                    x:198
                    y:406
                end:
                    x:282
                    y:473
            ,
                start:
                    x:348
                    y:178
                end:
                    x:364
                    y:195
            ,
                start:
                    x:432
                    y:31
                end:
                    x:516
                    y:100
            ,
                start:
                    x:432
                    y:151
                end:
                    x:516
                    y:219
            ,
                start:
                    x:432
                    y:272
                end:
                    x:516
                    y:341
            ,
                start:
                    x:603
                    y:178
                end:
                    x:620
                    y:196
            ,
                start:
                    x:432
                    y:406
                end:
                    x:516
                    y:476
            ,
                start:
                    x:682
                    y:319
                end:
                    x:701
                    y:334
            ,
                start:
                    x:762
                    y:293
                end:
                    x:850
                    y:361
            ,
                start:
                    x:906
                    y:317
                end:
                    x:923
                    y:334
            ,
                start:
                    x:908
                    y:434
                end:
                    x:923
                    y:450
        ]
]